url: https://popempire.github.io
baseurl:
permalink: :short_year:month:day-:slug/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

collections:

  pages:
    output: true
  
  notebooks:
    output: true

  songs:
    output: true
  
  song_ideas:
    output: true

  llotbw:
    output: true
  